### ISSUE TITLE
2017/1/11 ToDo List

### ISSUE THREAD

**Issue by Satoru-Nak** [Satoru-Nak/git-test#1]
- [x] intall git to the PC
- [ ] learn how to use git 
- [ ] create a memo for the things learned about git

**Comment by Satoru-Nak** [comment]
close #24
